KMSIPartsPortal_System/Controllers/WorkOrderInvoiceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using iTextSharp.text;
using iTextSharp.text.pdf;
using KMSIPartsPortal_System.Helpers;
using KMSIPartsPortal_System.Models;

namespace KMSIPartsPortal_System.Controllers
{
    public class WorkOrderInvoiceController : Controller
    {
        private kmsi_portalEntities db = new kmsi_portalEntities();

        // GET: WorkOrderInvoice
        public ActionResult Index()
        {
            if (Session["UserId"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        public ActionResult List()
        {
            try
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();

                // Paging Size
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int recordsTotal = 0;

                // Getting all Work Order Invoice data
                var woInvoiceData = (from wo in db.Invoices
                                     orderby wo.InvoiceDate ascending
                                     select new { wo.InvoiceID, wo.InvoiceDate, wo.InvoiceCode,
                                         wo.UnitSerialNumber, wo.UnitModel, wo.UnitCode,
                                         wo.PartsNumber, wo.CustomerCode, wo.ActualSMR, wo.AmountTotal });

                // Sorting
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                {
                    woInvoiceData = woInvoiceData.OrderBy(sortColumn + " " + sortColumnDir);
                }
                // Search
                if (!string.IsNullOrEmpty(searchValue))
                {
                    woInvoiceData = woInvoiceData.Where(wo => wo.InvoiceID.ToString().ToLower().Contains(searchValue.ToLower()) ||
                        wo.InvoiceDate.ToString().ToLower().Contains(searchValue.ToLower()) ||
                        wo.InvoiceCode.ToString().ToLower().Contains(searchValue.ToLower()) ||
                        wo.UnitSerialNumber.ToString().Contains(searchValue.ToLower()) ||
                        wo.UnitModel.ToString().ToLower().Contains(searchValue.ToLower()) ||
                        wo.UnitCode.ToString().ToLower().Contains(searchValue.ToLower()) ||
                        wo.PartsNumber.ToString().ToLower().Contains(searchValue.ToLower()) ||
                        wo.CustomerCode.ToString().ToLower().Contains(searchValue.ToLower()) ||
                        wo.ActualSMR.ToString().ToLower().Contains(searchValue.ToLower()) ||
                        wo.AmountTotal.ToString().ToLower().Contains(searchValue.ToLower())
                    );
                }

                // total number of rows count
                recordsTotal = woInvoiceData.Count();
                // Paging
                var data = woInvoiceData.Skip(skip).Take(pageSize).ToList();

                // Returning Json Data
                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
            }
            catch (Exception)
            {
                throw;
            }
        }

        // GET: WorkOrderInvoice/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // GET: WorkOrderInvoice/Create
        public ActionResult Create()
        {
            try
            {
                if (Session["UserId"] != null)
                {
                    using (kmsi_portalEntities db = new kmsi_portalEntities())
                    {
                        var getDataInvoice = (from i in db.Invoices
                                              select i.InvoiceCode).Max();

                        string dtYear = DateTime.Now.ToString("yy");
                        ViewBag.invoiceCode = (getDataInvoice != null) ? CodeGenerator.Generate("INV", "/", getDataInvoice) : "INV/" + "00" + dtYear + "/00001";
                        ViewBag.today = DateTime.Now.ToString("dddd, dd MMMM yyyy");

                        return View();
                    }
                }
                else
                {
                    return RedirectToAction("Login", "Account");
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
                return View();
            }
        }

        // POST: WorkOrderInvoice/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Invoice invoice)
        {
            try
            {
                using (kmsi_portalEntities db = new kmsi_portalEntities())
                {
                    if (ModelState.IsValid)
                    {
                        Contract contract = db.Contracts.Where(c => c.ContractCode == invoice.ContractCode && c.UnitSerialNumber == invoice.UnitSerialNumber).FirstOrDefault();

                        invoice.AmountTotal = contract.USDperHours * invoice.ActualSMR * invoice.Kurs;
                        invoice.InvoiceDate = DateTime.Now;
                        db.Invoices.Add(invoice);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
            }
            catch (Exception)
            {
                return View(invoice);
            }

            return View(invoice);
        }

        // GET: WorkOrderInvoice/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // POST: WorkOrderInvoice/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "InvoiceCode,ContractCode,CustomerCode,PartsNumber,UnitSerialNumber,InvoiceDate,UnitCode,UnitModel,CustomerName,RequestDeliveryDate,ActualSMR,AmountTotal,Kurs,InvoiceDueDate,TaxInvoiceNumber,InvoiceID")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(invoice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(invoice);
        }

        // GET: WorkOrderInvoice/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // POST: WorkOrderInvoice/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Invoice invoice = db.Invoices.Find(id);
            db.Invoices.Remove(invoice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Download(int[] ids)
        {
            try
            {
                using (kmsi_portalEntities db = new kmsi_portalEntities())
                {
                    DateTime dateTime = DateTime.Now;
                    string strCSVFileName = string.Format("INV_" + dateTime.ToString("yyyyMMdd_HHmm") + ".csv");
                    string handle = Guid.NewGuid().ToString();

                    using (MemoryStream memoryStream = new MemoryStream())
                    {
                        StreamWriter streamWriter = new StreamWriter(memoryStream);
                        streamWriter.WriteLine("\"InvoiceCode\",\"PartsNumber\",\"ActualSMR\"");

                        var listInvoice = db.Invoices.Where(w => ids.Contains(w.InvoiceID)).OrderBy(w => w.InvoiceCode);

                        foreach (var wo in listInvoice)
                        {

KMSIPartsPortal_System/Views/WorkOrderInvoice/Create.cshtml
@model KMSIPartsPortal_System.Models.Invoice

@{
    ViewBag.Title = "Invoice Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            @using (Html.BeginForm("Create", "WorkOrderInvoice", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="box-header with-border">
                    <div class="row">
                        <div class="col-md-6">
                            <h3 class="box-title"> @ViewBag.invoiceCode</h3>
                        </div>
                        <div class="col-md-6">
                            <h3 class="box-title" style="float:right;"> @ViewBag.today</h3>
                        </div>
                    </div>
                </div>

                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.InvoiceCode, new { Value = ViewBag.invoiceCode })
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.UnitSerialNumber, htmlAttributes: new { @class = "control-label col-md-4" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.UnitSerialNumber, new { htmlAttributes = new { @class = "form-control", @id = "search-unit-sn" } })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.CustomerCode, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.CustomerCode, new { htmlAttributes = new { @class = "form-control disabled", @readonly = true } })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.UnitCode, htmlAttributes: new { @class = "control-label col-md-4" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.UnitCode, new { htmlAttributes = new { @class = "form-control disabled", @readonly = true } })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control disabled", @readonly = true } })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.UnitModel, htmlAttributes: new { @class = "control-label col-md-4" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.UnitModel, new { htmlAttributes = new { @class = "form-control disabled", @readonly = true } })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.TaxInvoiceNumber, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.TaxInvoiceNumber, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.TaxInvoiceNumber, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ContractCode, htmlAttributes: new { @class = "control-label col-md-4" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.ContractCode, new { htmlAttributes = new { @class = "form-control disabled", @readonly = true } })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Kurs, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.Kurs, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.TaxInvoiceNumber, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ActualSMR, htmlAttributes: new { @class = "control-label col-md-4" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.ActualSMR, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ActualSMR, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.InvoiceDueDate, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    <div class="input-group invoice-due-dt date">
                                        @Html.EditorFor(model => model.InvoiceDueDate, new { htmlAttributes = new { @class = "form-control" } })
                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                        @Html.ValidationMessageFor(model => model.InvoiceDueDate, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer" align="right">
                    <a href="@Url.Action("Index", "WorkOrderInvoice")" class="btn btn-sm btn-flat btn-danger">CANCEL</a>
                    <button type="submit" class="btn btn-sm btn-flat bg-navy">SUBMIT</button>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $('.invoice-due-dt.date').datepicker({
                autoclose: true,
                format: "yyyy-mm-dd"
            });

            $('#search-unit-sn').autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: '@Url.Action("GetSearchUnit", "Contracts")',
                        type: "POST",
                        dataType: "json",
                        data: { Prefix: $('#search-unit-sn').val() },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return { label: item.Contract.UnitSerialNumber, value: item.Contract.UnitSerialNumber, data: item };
                            }));
                        },
                        error: function (xhr, status, error) {
                            console.log("Error")
                        }
                    });
                },
                select: function (e, response) {
                    $('#UnitCode').val(response.item.data.Contract.UnitCode);
                    $('#UnitModel').val(response.item.data.Contract.UnitModel);
                    $('#ContractCode').val(response.item.data.Contract.ContractCode);
                    $('#CustomerCode').val(response.item.data.Customer.CustomerCode);
                    $('#CustomerName').val(response.item.data.Customer.CustomerName);
                }
            });
        });
    </script>
}

KMSIPartsPortal_System/Views/WorkOrderInvoice/Delete.cshtml
@model KMSIPartsPortal_System.Models.Invoice

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.InvoiceCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvoiceCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContractCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContractCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PartsNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartsNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitSerialNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitSerialNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvoiceDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvoiceDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitModel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitModel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestDeliveryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestDeliveryDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActualSMR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActualSMR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AmountTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmountTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kurs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kurs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvoiceDueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvoiceDueDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaxInvoiceNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaxInvoiceNumber)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KMSIPartsPortal_System/Views/WorkOrderInvoice/Details.cshtml
@model KMSIPartsPortal_System.Models.Invoice

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-6" align="left">
        <a href="@Url.Action("DownloadPdf", "WorkOrderInvoice", new { code = Model.InvoiceCode })" class="btn btn-sm btn-primary btn-flat"> Download Invoice</a>
    </div>

    <div class="col-md-6" align="right">
        <a href="@Url.Action("Index", "WorkOrderInvoice")" class="btn btn-sm btn-flat bg-navy"> Back To Invoice List</a>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            @using (Html.BeginForm("", "", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="box-header with-border">
                    <div class="row">
                        <div class="col-md-6">
                            <h3 class="box-title"> @Html.DisplayFor(model => model.InvoiceCode)</h3>
                        </div>
                        <div class="col-md-6">
                            <h3 class="box-title" style="float: right"> @Html.DisplayFor(model => model.InvoiceDate)</h3>
                        </div>
                    </div>
                </div>

                <div class="box-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.UnitSerialNumber, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.UnitSerialNumber, new { htmlAttributes = new { @class = "form-control disabled", @readonly = true } })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.CustomerCode, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.CustomerCode, new { htmlAttributes = new { @class = "form-control disabled", @readonly = true } })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.UnitCode, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.UnitCode, new { htmlAttributes = new { @class = "form-control disabled", @readonly = true } })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control disabled", @readonly = true } })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.UnitModel, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.UnitModel, new { htmlAttributes = new { @class = "form-control disabled", @readonly = true } })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.TaxInvoiceNumber, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.TaxInvoiceNumber, new { htmlAttributes = new { @class = "form-control disabled", @readonly = true } })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ActualSMR, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.ActualSMR, new { htmlAttributes = new { @class = "form-control disabled", @readonly = true } })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.InvoiceDueDate, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.InvoiceDueDate, new { htmlAttributes = new { @class = "form-control disabled", @readonly = true } })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Kurs, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.Kurs, new { htmlAttributes = new { @class = "form-control disabled", @readonly = true } })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.AmountTotal, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    @Html.EditorFor(model => model.AmountTotal, new { htmlAttributes = new { @class = "form-control disabled", @readonly = true } })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>