KMSIPartsPortal_System/Models/WorkOrder.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMSIPartsPortal_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public int WorkOrderID { get; set; }
        public string WorkOrderCode { get; set; }
        public Nullable<int> ContractID { get; set; }
        public string ContractCode { get; set; }
        public string CustomerCode { get; set; }
        public string PartsNumber { get; set; }
        public string UnitSerialNumber { get; set; }
        public Nullable<System.DateTime> WorkOrderDate { get; set; }
        public string UnitCode { get; set; }
        public string UnitModel { get; set; }
        public string TypeOfProblem { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> RequestDeliveryDate { get; set; }
        public string Site { get; set; }
        public string Status { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public string Comments { get; set; }
        public string AgreementNumber { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
    }
}

KMSIPartsPortal_System/Controllers/WorkOrderController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.text.pdf.draw;
using KMSIPartsPortal_System.Helpers;
using KMSIPartsPortal_System.Models;

namespace KMSIPartsPortal_System.Controllers
{
    public class WorkOrderController : Controller
    {
        // GET: WorkOrder/Index
        public ActionResult Index(string code, string unit)
        {
            if (Session["UserId"] != null)
            {
                using (kmsi_portalEntities db = new kmsi_portalEntities())
                {
                    if (code == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    ViewBag.ContractCode = code;
                    ViewBag.UnitSerialNumber = unit;

                    return View();
                }
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        public ActionResult List()
        {
            try
            {
                // Creating instance of DatabaseContext class
                using (kmsi_portalEntities db = new kmsi_portalEntities())
                {
                    var draw = Request.Form.GetValues("draw").FirstOrDefault();
                    var start = Request.Form.GetValues("start").FirstOrDefault();
                    var length = Request.Form.GetValues("length").FirstOrDefault();
                    var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                    var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                    var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();

                    // Paging Size
                    int pageSize = length != null ? Convert.ToInt32(length) : 0;
                    int skip = start != null ? Convert.ToInt32(start) : 0;
                    int recordsTotal = 0;

                    // Getting all Work Order data
                    var workOrderData = db.WorkOrders.AsEnumerable()
                                    .Where(x => x.ContractCode == Request.Form.GetValues("ContractCode").FirstOrDefault() && x.UnitSerialNumber == Request.Form.GetValues("UnitSerialNumber").FirstOrDefault() && x.ApprovalStatus == 1)
                                    .GroupBy(x => x.WorkOrderCode)
                                    .Select(group => group.First());

                    // Sorting
                    if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                    {
                        workOrderData = workOrderData.OrderBy(sortColumn + " " + sortColumnDir);
                    }
                    // Search
                    if (!string.IsNullOrEmpty(searchValue))
                    {
                        workOrderData = workOrderData.Where(w => w.WorkOrderCode.ToString().ToLower().Contains(searchValue.ToLower())
                            || w.WorkOrderDate.ToString().ToLower().Contains(searchValue.ToLower())
                            || w.UnitSerialNumber.ToLower().Contains(searchValue.ToLower())
                            || w.UnitCode.ToLower().Contains(searchValue.ToLower())
                            || w.UnitModel.ToString().ToLower().Contains(searchValue.ToLower())
                            || w.AgreementNumber.ToString().ToLower().Contains(searchValue.ToLower())
                            || w.CustomerCode.ToLower().Contains(searchValue.ToLower())
                            || w.CustomerName.ToLower().Contains(searchValue.ToLower())
                            || w.RequestDeliveryDate.ToString().ToLower().Contains(searchValue.ToLower())
                            || w.Site.ToLower().Contains(searchValue.ToLower())
                            || (w.Comments != null && w.Comments.ToLower().Contains(searchValue.ToLower()))
                        );
                    }

                    // total number of rows count
                    recordsTotal = workOrderData.Count();

                    // Paging
                    var data = workOrderData.Skip(skip).Take(pageSize).ToList();
                    // Returning Json Data
                    return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
                }
            }
            catch (Exception ex)
            {
                var filename = AppDomain.CurrentDomain.BaseDirectory + "App_Data\\" + "log\\" + "logErrors.txt";
                var sw = new System.IO.StreamWriter(filename, true);
                sw.WriteLine(DateTime.Now.ToString() + " " + ex.Message + " " + ex.InnerException);
                sw.Close();

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        // GET: WorkOrder/Details/5
        public ActionResult Details(string code)
        {
            try
            {
                if (Session["UserId"] != null)
                {
                    using (kmsi_portalEntities db = new kmsi_portalEntities())
                    {
                        var workOrderData = db.WorkOrders
                            .Where(wo => wo.WorkOrderCode == code)
                            .OrderBy(wo => wo.WorkOrderID)
                            .ToList();
                        var woSummaryData = workOrderData.FirstOrDefault();

                        ViewBag.woSummaryData = woSummaryData;
                        ViewBag.pnData = workOrderData;
                        return View();
                    }
                }
                else
                {
                    return RedirectToAction("Login", "Account");
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        // GET: WorkOrder/Create
        public ActionResult Create(string code, string unit)
        {
            try
            {
                if (Session["UserId"] != null)
                {
                    using (kmsi_portalEntities db = new kmsi_portalEntities())
                    {
                        if (code == null)
                        {
                            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                        }
                        List<Contract> contract = db.Contracts.Where(c => c.ContractCode == code && c.UnitSerialNumber == unit).ToList();
                        var contractData = contract.FirstOrDefault();
                        Customer customer = db.Customers.Where(c => c.CustomerCode == contractData.CustomerId).FirstOrDefault();
                        var getDataWorkOrder = (from wo in db.WorkOrders
                                                select wo.WorkOrderCode).Max();

                        string dtYear = DateTime.Now.ToString("yy");

                        ViewBag.contractData = contract.FirstOrDefault();
                        ViewBag.customerData = customer;
                        ViewBag.workOrderCode = getDataWorkOrder != null ? CodeGenerator.Generate("WO", "-", getDataWorkOrder) : "WO-" + "00" + dtYear + "-00001";
                        ViewBag.today = DateTime.Now.ToString("dddd, dd MMMM yyyy");

                        return View();
                    }
                }
                else
                {
                    return RedirectToAction("Login", "Account");
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
        }

        // POST: WorkOrder/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(WorkOrder workOrder)
        {
            try
            {
                using (kmsi_portalEntities db = new kmsi_portalEntities())
                {
                    var errMsg = TempData["ErrorMessage"] as string;

                    if (ModelState.IsValid)
                    {
                        string[] PartsNumber = Request.Form.GetValues("PartsNumber[]");
                        string[] Description = Request.Form.GetValues("Description[]");
                        string[] Quantity = Request.Form.GetValues("Quantity[]");
                        string[] Remark = Request.Form.GetValues("Remark[]");

                        var i = 0;
                        foreach (var item in PartsNumber)
                        {
                            workOrder.WorkOrderDate = DateTime.Now;
                            workOrder.PartsNumber = item;
                            workOrder.Quantity = Convert.ToInt32(Quantity[i]);
                            workOrder.Description = Description[i];
                            workOrder.Remarks = Remark[i];
                            workOrder.ApprovalStatus = 1;
                            db.WorkOrders.Add(workOrder);
                            db.SaveChanges();
                            i++;
                        }

                        Int32 UserID = Convert.ToInt32(Session["UserId"]);
                        User user = new User();
                        user = db.Users.Find(UserID);
                        var woData = db.WorkOrders.Where(x => x.WorkOrderCode == workOrder.WorkOrderCode).ToList();

KMSIPartsPortal_System/Views/WorkOrder/Details.cshtml
@model KMSIPartsPortal_System.Models.WorkOrder

@{
    ViewBag.Title = "Work Order Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-12">
        <div class="pull-left">
            <a href="@Url.Action("DownloadPdf", "WorkOrder", new { code = ViewBag.woSummaryData.WorkOrderCode })" class="btn btn-sm btn-flat btn-success"> Download Work Order</a>
        </div>
        <div class="pull-right">
            <a href="@Url.Action("Index", "WorkOrder", new { code = ViewBag.woSummaryData.ContractCode, unit = ViewBag.woSummaryData.UnitSerialNumber })" class="btn btn-sm btn-flat bg-navy"> Back To Work Order List</a>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            @using (Html.BeginForm("Approval", "WorkOrder", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="box-header with-border">
                    <div class="row">
                        <div class="col-md-6">
                            <h3 class="box-title"> @ViewBag.woSummaryData.WorkOrderCode </h3>
                        </div>
                        <div class="col-md-6">
                            <h3 class="box-title" style="float: right;"> @ViewBag.woSummaryData.WorkOrderDate.ToString("dddd, dd MMMM yyyy") </h3>
                        </div>
                    </div>
                </div>

                @Html.AntiForgeryToken()
                @Html.Hidden("WorkOrderCode", (object)ViewBag.woSummaryData.WorkOrderCode)
                @Html.Hidden("ContractCode", (object)ViewBag.woSummaryData.ContractCode)
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.UnitSerialNumber, htmlAttributes: new { @class = "control-label col-md-4" })
                                <div class="col-md-8">
                                    @Html.TextBoxFor(model => model.UnitSerialNumber, new { @class = "form-control disabled", @Value = ViewBag.woSummaryData.UnitSerialNumber, @readonly = true })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.CustomerCode, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    @Html.TextBoxFor(model => model.CustomerCode, new { @class = "form-control disabled", @Value = ViewBag.woSummaryData.CustomerCode, @readonly = true })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.UnitCode, htmlAttributes: new { @class = "control-label col-md-4" })
                                <div class="col-md-8">
                                    @Html.TextBoxFor(model => model.UnitCode, new { @class = "form-control disabled", @Value = ViewBag.woSummaryData.UnitCode, @readonly = true })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    @Html.TextBoxFor(model => model.CustomerName, new { @class = "form-control disabled", @Value = ViewBag.woSummaryData.CustomerName, @readonly = true })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.UnitModel, htmlAttributes: new { @class = "control-label col-md-4" })
                                <div class="col-md-8">
                                    @Html.TextBoxFor(model => model.UnitModel, new { @class = "form-control disabled", @Value = ViewBag.woSummaryData.UnitModel, @readonly = true })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.RequestDeliveryDate, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    @Html.TextBoxFor(model => model.RequestDeliveryDate, new { @class = "form-control disabled", @Value = ViewBag.woSummaryData.RequestDeliveryDate != null ? ViewBag.woSummaryData.RequestDeliveryDate.ToString("yyyy-MM-dd") : "", @readonly = true })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.AgreementNumber, htmlAttributes: new { @class = "control-label col-md-4" })
                                <div class="col-md-8">
                                    @Html.TextBoxFor(model => model.AgreementNumber, new { @class = "form-control disabled", @Value = ViewBag.woSummaryData.AgreementNumber, @readonly = true })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Site, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align: left;" })
                                <div class="col-md-8">
                                    @Html.TextBoxFor(model => model.Site, new { @class = "form-control disabled", @Value = ViewBag.woSummaryData.Site, @readonly = true })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                @Html.LabelFor(model => model.PartsNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <table id="work-order-form" class="table table-bordered table-striped" style="width: 100%">
                                        <thead>
                                            <tr>
                                                <th>No.</th>
                                                <th>Parts Number</th>
                                                <th>Description</th>
                                                <th>Qty</th>
                                                <th>Remarks</th>
                                            </tr>
                                        </thead>
                                        @{
                                            int counter = 1;

                                            foreach (var parts in ViewBag.pnData)
                                            {
                                                <tbody>
                                                    <tr>
                                                        <td align="center">@Html.Label("", counter.ToString(), new { @class = "control-label" })</td>
                                                        <td>@Html.TextBoxFor(model => model.PartsNumber, new { @class = "form-control disabled", @Value = parts.PartsNumber, @readonly = true })</td>
                                                        <td>@Html.TextBoxFor(model => model.Description, new { @class = "form-control disabled", @Value = parts.Description, @readonly = true })</td>
                                                        <td>@Html.TextBoxFor(model => model.Quantity, new { @class = "form-control disabled", @Value = parts.Quantity, @readonly = true })</td>
                                                        <td>@Html.TextBoxFor(model => model.Remarks, new { @class = "form-control disabled", @Value = parts.Remarks, @readonly = true })</td>
                                                    </tr>
                                                </tbody>
                                                counter++;
                                            }
                                        }
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    <textarea class="form-control" rows="4" style="resize: none;" readonly>@ViewBag.woSummaryData.Comments</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                if ((Session["RoleId"] == null || (int)Session["RoleId"] == 4) && ViewBag.woSummaryData.ApprovalStatus == 1)
                {
                    <div class="box-footer" align="right">
                        <button type="submit" class="btn btn-sm btn-flat bg-navy" name="mode" value="approve">APPROVE</button>
                        <button type="submit" class="btn btn-sm btn-flat btn-danger" name="mode" value="reject">REJECT</button>
                    </div>
                }
            }

        </div>
    </div>
</div>

KMSIPartsPortal_System/Views/WorkOrder/Index.cshtml
@model IEnumerable<KMSIPartsPortal_System.Models.WorkOrder>

@{
    ViewBag.Title = "Work Order";
}
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-body">
                <div class="row">
                    <div class="col-md-6">
                        @if (Session["RoleId"] == null || (int)Session["RoleId"] == 3)
                        {
                            <a id="btn-new-workorder" href="@Url.Action("Create", "WorkOrder", new { code = ViewBag.ContractCode, unit = ViewBag.UnitSerialNumber })" class="btn btn-sm btn-success btn-flat">Create new</a>
                            <a id="btn-open-workorder" href="javascript:void(0)" class="btn btn-sm bg-purple btn-flat disabled">Open</a>
                            <a id="btn-download-workorder" href="javascript:void(0)" class="btn btn-sm btn-primary btn-flat disabled">Download CSV</a>
                        }
                        else
                        {
                            <a id="btn-open-workorder" href="javascript:void(0)" class="btn btn-sm bg-purple btn-flat disabled">Open</a>
                            <a id="btn-download-workorder" href="javascript:void(0)" class="btn btn-sm btn-primary btn-flat disabled">Download CSV</a>
                        }
                    </div>
                    <div class="col-md-6" align="right">
                        <a href="@Url.Action("Index", "Unit", new { code = ViewBag.ContractCode })" class="btn btn-sm btn-flat bg-navy"> Back To Unit List</a>
                    </div>
                </div>
                <br />
                @Html.Hidden("ContractCode", (object)ViewBag.ContractCode)
                @Html.Hidden("UnitSerialNumber", (object)ViewBag.UnitSerialNumber)
                <table id="work-order-dt" class="table table-bordered table-striped" style="width: 100%">
                    <thead>
                        <tr>
                            <th>@Html.CheckBox("selectAll", false, htmlAttributes: new { @class = "form-control", @id = "select-all" })</th>
                            <th>No.</th>
                            <th>@Html.DisplayNameFor(model => model.WorkOrderCode)</th>
                            <th>@Html.DisplayNameFor(model => model.WorkOrderDate)</th>
                            <th>@Html.DisplayNameFor(model => model.UnitSerialNumber)</th>
                            <th>@Html.DisplayNameFor(model => model.UnitCode)</th>
                            <th>@Html.DisplayNameFor(model => model.UnitModel)</th>
                            <th>@Html.DisplayNameFor(model => model.AgreementNumber)</th>
                            <th>@Html.DisplayNameFor(model => model.CustomerCode)</th>
                            <th>@Html.DisplayNameFor(model => model.CustomerName)</th>
                            <th>@Html.DisplayNameFor(model => model.RequestDeliveryDate)</th>
                            <th>@Html.DisplayNameFor(model => model.Site)</th>
                            <th>@Html.DisplayNameFor(model => model.Comments)</th>
                        </tr>
                    </thead>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            function turn_on_iCheck() {
                $('input[type="checkbox"], input[type="radio"]').iCheck({
                    checkboxClass: "icheckbox_minimal-blue",
                    radioClass: "iradio_minimal-blue"
                }).on('ifChanged', function (e) {
                    var length = $('input[name="checkedWorkOrderCode"]:checked').length;

                    if (length == 1) {
                        $('#btn-open-workorder').removeClass('disabled');
                    } else {
                        $('#btn-open-workorder').addClass('disabled');
                    }

                    if (length >= 1) {
                        $('#btn-download-workorder').removeClass('disabled');
                    } else {
                        $('#btn-download-workorder').addClass('disabled');
                    }

                    if (length == $('input[name="checkedWorkOrderCode"]').length) {
                        $('#select-all').iCheck('check');
                    } else {
                        $('#select-all').iCheck('uncheck');
                    }
                });

                $('#select-all').on('ifClicked', function () {
                    if ($('#select-all').is(':checked')) {
                        $('input[name="checkedWorkOrderCode"]').iCheck('uncheck');
                    } else {
                        $('input[name="checkedWorkOrderCode"]').iCheck('check');
                    }
                });
            }

            $('#work-order-dt').DataTable({
                "processing": true,
                "serverSide": true,
                "filter": true,
                "pageLength": 10,
                "ajax": {
                    "url": "/WorkOrder/List",
                    "data": { ContractCode: $('#ContractCode').val(), UnitSerialNumber: $('#UnitSerialNumber').val() },
                    "type": "POST",
                    "datatype": "json"
                },
                "columnDefs": [
                    {
                        "targets": [0, 1, 12],
                        "className": 'text-center',
                        "searchable": false,
                        "sortable": false
                    },
                    {
                        "targets": [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
                        "className": 'text-center'
                    }
                ],
                "order": [[3, 'desc']],
                "columns": [
                    {
                        "data": null,
                        "render": function (data, type, full, meta) {
                            return '<input type="checkbox" name="checkedWorkOrderCode" value="' + full.WorkOrderCode + '">';
                        }
                    },
                    {
                        "data": null,
                        "render": function (data, type, full, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                        }
                    },
                    { "data": "WorkOrderCode", "name": "WorkOrderCode" },
                    {
                        "data": "WorkOrderDate", "name": "WorkOrderDate",
                        "render": function (data, type, full, meta) {
                            if (data) {
                                return moment(data).format('YYYY-MM-DD');
                            } else {
                                return "";
                            }
                        }
                    },
                    { "data": "UnitSerialNumber", "name": "UnitSerialNumber" },
                    { "data": "UnitCode", "name": "UnitCode" },
                    { "data": "UnitModel", "name": "UnitModel" },
                    { "data": "AgreementNumber", "name": "AgreementNumber" },
                    { "data": "CustomerCode", "name": "CustomerCode" },
                    { "data": "CustomerName", "name": "CustomerName" },
                    {
                        "data": "RequestDeliveryDate", "name": "RequestDeliveryDate",
                        "render": function (data, type, full, meta) {
                            if (data) {
                                return moment(data).format('YYYY-MM-DD');
                            } else {
                                return "";
                            }
                        }
                    },
                    { "data": "Site", "name": "Site" },
                    { "data": "Comments", "name": "Comments" },
                ]
            });

            $('#work-order-dt').on('draw.dt', function () {
                turn_on_iCheck();
            });

            $('#btn-open-workorder').click(function () {
                var code = $('input[name="checkedWorkOrderCode"]:checked').val();
                window.location.href = "/WorkOrder/Details/?code=" + code + "";
            });

            $('#btn-download-workorder').click(function () {
                var codes = [];
                $.each($('input[name="checkedWorkOrderCode"]:checked'), function () {
                    codes.push($(this).val());
                });

                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "/WorkOrder/PostDownloadPartial",
                    dataType: "JSON",
                    data: {
                        codes: codes
                    },
                    success: function (resultData) {
                        if (resultData.success) {
                            window.location = '/WorkOrder/DownloadCsv?fileGuid=' + resultData.FileGuid + '&fileName=' + resultData.FileName;
                        }
                    },
                    error: function (xhr, status, error) {

                    }
                });
            });
        });
    </script>
}